### ISSUE TITLE
Display the env name in the terminal

### ISSUE THREAD

**Issue by Vayel** [berdario/pew#45] opened 2015-01-03 14:01 UTC
Hi!

Currently, the env name is not displayed in the terminal as virtualenv does. It's hard to know if an env is activated, on which we are working... This script seems to do the job:

```
function venv_ps1(){
    test -n "$VIRTUAL_ENV" && echo "($(basename "$VIRTUAL_ENV")) "
}
PS1="$(venv_ps1)$PS1"
```

From [here](http://hashbang.fr/de-virtualenvwrapper-a-pew.html).

**Comment by berdario** [comment] 2015-01-03 15:06
Yes, this is [known and documented](https://github.com/berdario/pew#workon-opens-a-new-shell-prompt)

Unfortunately, there's no cross platform way to fix this. Automatically modifying the user's configuration file could be a recipe for disaster.

Detecting if the user's prompt doesn't have such information and warn him about it could be an improvement, and a good enough workaround for this issue. I attempted [something like that](https://github.com/berdario/pew/commit/0adc21ca55118dea9bc334ee5ec7f131abed1f7b), but unfortunately that's impossible due to the fact that `PS1` is not a proper env variable, but it's "magic internal state" (or at least it seems to behave like this):

    bash -lc "echo \$PS1"

doesn't echo anything, nor does

    echo "echo \$PS1" | bash -l

work

I even tried by supplying a fake tty (maybe the problem is that `bash` doesn't create the `PS1` unless it's a tty)

```python
from subprocess import Popen, PIPE
import pty
import os
import sys
import tty

master, slave = pty.openpty()
p = Popen(['bash', '-l'], stdin=slave, stdout=PIPE, stderr=PIPE)
pin = os.fdopen(master, 'w')
tty.setcbreak(sys.stdin)

pin.write('echo $SHELL\n')
pin.write('echo $PS1\n')
pin.write('exit\n')
print(p.stdout.readline())
print(p.stdout.readline())
print(p.stdout.readline())
```

For now I'll leave this issue open, in case you have some insights/tips to share, but since this bug cannot be acted upon, I'll otherwise close it in the following days

**Comment by ryanhiebert** [comment] 2015-01-03 20:27
I have this in my `.bashrc`:

```bash
export PS1="$ "
if [ -n "`pew show`" ]; then
    export PS1="(`pew show`)$PS1"
fi
```

**Comment by ajschumacher** [comment] 2015-01-08 21:32
Hi @ryanhiebert! For me, your solution displays an annoying "pew-show [venv]" when there isn't a venv active. In bash it seems very good to use the `"($(basename "$VIRTUAL_ENV")) "` solution from @Vayel. Please let me know if I'm missing a good reason to prefer using `pew show` - thanks!

**Comment by ryanhiebert** [comment] 2015-01-08 22:17
Oh, sorry about that. I misunderstood what pew show does. My fault. (I re-created `pew show` in my own version of `pew` that did what I _thought_ `pew show` did, but that's not what `pew` does). So the `"($(basename "$VIRTUAL_ENV")) "` is a good way to go then.

Sorry for the confusion.

**Comment by berdario** [comment] 2015-09-09 11:30
> Automatically modifying the user's configuration file could be a recipe for disaster.

I changed idea, upon seeing how tools like [opam](http://opam.ocaml.org/doc/FAQ.html#Whydoesopaminitneedtoaddstufftomyinitscriptswhyisevalopamconfigenvneeded) (and others) handle it

Leaving the choice to the user (and defaulting to not modifying anything, while explaining how to do it manually) seems a good choice.
Also, thanks to the simplified entry points (there's only one now), it's easier/cleaner to add a check for the first-time-setup

So now, when [running pew for the first time](https://github.com/berdario/pew/commit/686c59e63da8e3b81c288190095d023c8ea13a6f) in a new $WORKON_HOME, it will check if your $SHELL config file includes pew's "shell config" (which loads completions and provides prompt customization)

**Closed by berdario** 2015-09-09 11:30 UTC
